package com.StuffieDispenser.web;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.StuffieDispenser.business.Stuffie;
import com.StuffieDispenser.business.StuffieRepository;
import com.StuffieDispenser.util.JsonResponse;

@Controller
@RequestMapping(path = "/stuffie")
public class StuffieController {
	// This means to get the bean called StuffieRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired // like static method, no new() required, creating a bean (big POJO)
	private StuffieRepository stuffieRepository;

	// get all stuffies
	@GetMapping("/")
	public @ResponseBody JsonResponse getAllstuffie() {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(stuffieRepository.findAll()); // returns all instance of stuffie type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get stuffies - pagination version
	@GetMapping("")
	public @ResponseBody JsonResponse getstuffies(@RequestParam int start, @RequestParam int limit) {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(stuffieRepository.findAll(PageRequest.of(start, limit))); // returns all
																									// instance
																									// of stuffie type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get method using @RequestParam
//	@GetMapping("/get") // @RequestParam - have to add "?id=?"
//	public @ResponseBody Optional<stuffie> getstuffieById(@RequestParam int id) { // returns the stuffie
////		Optional<stuffie> u = stuffieRepository.findById(id);
//		return getstuffie(id); // calls path variable get method
//	}

	// get method using path variable
	@GetMapping("/{id}")
	public @ResponseBody JsonResponse getstuffie(@PathVariable int id) { // returns the stuffie
		JsonResponse jr = null; // instantiates JsonResponse as an object
		try {
			Optional<Stuffie> u = stuffieRepository.findById(id);
			if (u.isPresent()) {
				// good call to database - return a valid stuffie
				jr = JsonResponse.getInstance(u); // return stuffie object
			} else {
				jr = JsonResponse.getInstance(new Exception("No stuffie Found for ID: " + id));
			}
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// add an stuffie
	@PostMapping(path = "/")
	public @ResponseBody JsonResponse addNewstuffie(@RequestBody Stuffie g) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET (read) or @RequestBody
		// POST (update and delete)
		// request
//		return u;
//		JsonResponse jr = null;
//		jr = JsonResponse.getInstance(savestuffie(u));
		return savestuffie(g);
	}

	// update an stuffie - changed from Post to PutMapping
	@PutMapping("/{id}")
	public @ResponseBody JsonResponse updatestuffie(@PathVariable int id, @RequestBody Stuffie s) {
//		u = stuffieRepository.save(u);
		return savestuffie(s);
//		return u;
	}

	private @ResponseBody JsonResponse savestuffie(Stuffie s) {
		JsonResponse jr = null;
		try {
			stuffieRepository.save(s);
			jr = JsonResponse.getInstance(s);
		} catch (DataIntegrityViolationException dive) {
			// TODO better way to handle exceptions
			jr = JsonResponse.getInstance(dive);
			jr.setErrors(dive.getMessage());
		}
		return jr;
	}

	// delete an stuffie
	@DeleteMapping("/{id}")
	public @ResponseBody JsonResponse removeUser(@PathVariable int id) { // remove the stuffie by id
		JsonResponse jr = null;
		Optional<Stuffie> s = stuffieRepository.findById(id);
		if (s.isPresent()) {
			stuffieRepository.deleteById(id);
			jr = JsonResponse.getInstance(s);
		} else {
			jr = JsonResponse.getInstance("User ID " + id + " was not successful deleted.");
		}
		return jr;
	}
//	// get stuffie by Gender
//	@GetMapping("/getByGender")
//	public @ResponseBody JsonResponse getstuffieByGender(@RequestBody stuffie stuffie) { // returns the user
//		return JsonResponse.getInstance(stuffieRepository.findByGender(stuffie.getGender()));
//	}
}
