package com.bmdb.web;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bmdb.business.Credits;
import com.bmdb.business.CreditsRepository;
import com.bmdb.util.JsonResponse;

@Controller
@RequestMapping(path = "/credits")
public class CreditController {
	// This means to get the bean called creditsRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired // like static method, no new() required, creating a bean (big POJO)
	private CreditsRepository creditsRepository;

	// get all credits
	@GetMapping("/")
	public @ResponseBody JsonResponse getAllCredits() {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(creditsRepository.findAll()); // returns all instance of Credits type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get Credits - pagination version
	@GetMapping("")
	public @ResponseBody JsonResponse getCredits(@RequestParam int start, @RequestParam int limit) {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(creditsRepository.findAll(PageRequest.of(start, limit))); // returns all
																									// instance
																									// of Credits type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get method using @RequestParam
//	@GetMapping("/get") // @RequestParam - have to add "?id=?"
//	public @ResponseBody Optional<Credits> getCreditsById(@RequestParam int id) { // returns the Credits
////		Optional<Credits> u = creditsRepository.findById(id);
//		return getCredits(id); // calls path variable get method
//	}

	// get method using path variable
	@GetMapping("/{id}")
	public @ResponseBody JsonResponse getCredits(@PathVariable int id) { // returns the Credits
		JsonResponse jr = null; // instantiates JsonResponse as an object
		try {
			Optional<Credits> c = creditsRepository.findById(id);
			if (c.isPresent()) {
				// good call to database - return a valid Credits
				jr = JsonResponse.getInstance(c); // return Credits object
			} else {
				jr = JsonResponse.getInstance(new Exception("No Credits Found for ID: " + id));
			}
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// add an Credits
	@PostMapping(path = "/")
	public @ResponseBody JsonResponse addNewCredits(@RequestBody Credits a) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET (read) or @RequestBody
		// POST (update and delete)
		// request
//		return u;
//		JsonResponse jr = null;
//		jr = JsonResponse.getInstance(saveCredits(u));
		return saveCredits(a);
	}

	// update an Credits - changed from Post to PutMapping
	@PutMapping("/{id}")
	public @ResponseBody JsonResponse updateCredits(@PathVariable int id, @RequestBody Credits a) {
//		u = creditsRepository.save(u);
		return saveCredits(a);
//		return u;
	}

	private @ResponseBody JsonResponse saveCredits(Credits a) {
		JsonResponse jr = null;
		try {
			creditsRepository.save(a);
			jr = JsonResponse.getInstance(a);
		} catch (DataIntegrityViolationException dive) {
			// TODO better way to handle exceptions
			jr = JsonResponse.getInstance(dive);
			jr.setErrors(dive.getMessage());
		}
		return jr;
	}

	// delete an Credits
	@DeleteMapping("/{id}")
	public @ResponseBody JsonResponse removeUser(@PathVariable int id) { // remove the Credits by id
		JsonResponse jr = null;
		Optional<Credits> a = creditsRepository.findById(id);
		if (a.isPresent()) {
			creditsRepository.deleteById(id);
			jr = JsonResponse.getInstance(a);
		} else {
			jr = JsonResponse.getInstance("User ID " + id + " was not successful deleted.");
		}
		return jr;
	}

	// get Credits by Movie ID
	@GetMapping("/getByMovie")
	public @ResponseBody JsonResponse getCreditsByGender(@RequestBody Credits Credits) { // returns the user
		return JsonResponse.getInstance(creditsRepository.findByMovie(Credits.getMovie()));
	}
}
