package com.bmdb.web;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bmdb.business.Genre;
import com.bmdb.business.GenreRepository;
import com.bmdb.util.JsonResponse;

@Controller
@RequestMapping(path = "/genre")
public class GenreController {
	// This means to get the bean called genreRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired // like static method, no new() required, creating a bean (big POJO)
	private GenreRepository genreRepository;

	// get all genres
	@GetMapping("/")
	public @ResponseBody JsonResponse getAllGenre() {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(genreRepository.findAll()); // returns all instance of genre type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get genres - pagination version
	@GetMapping("")
	public @ResponseBody JsonResponse getGenres(@RequestParam int start, @RequestParam int limit) {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(genreRepository.findAll(PageRequest.of(start, limit))); // returns all
																									// instance
																									// of genre type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get method using @RequestParam
//	@GetMapping("/get") // @RequestParam - have to add "?id=?"
//	public @ResponseBody Optional<genre> getgenreById(@RequestParam int id) { // returns the genre
////		Optional<genre> u = genreRepository.findById(id);
//		return getgenre(id); // calls path variable get method
//	}

	// get method using path variable
	@GetMapping("/{id}")
	public @ResponseBody JsonResponse getGenre(@PathVariable int id) { // returns the genre
		JsonResponse jr = null; // instantiates JsonResponse as an object
		try {
			Optional<Genre> u = genreRepository.findById(id);
			if (u.isPresent()) {
				// good call to database - return a valid genre
				jr = JsonResponse.getInstance(u); // return genre object
			} else {
				jr = JsonResponse.getInstance(new Exception("No genre Found for ID: " + id));
			}
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// add an genre
	@PostMapping(path = "/")
	public @ResponseBody JsonResponse addNewGenre(@RequestBody Genre g) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET (read) or @RequestBody
		// POST (update and delete)
		// request
//		return u;
//		JsonResponse jr = null;
//		jr = JsonResponse.getInstance(savegenre(u));
		return saveGenre(g);
	}

	// update an genre - changed from Post to PutMapping
	@PutMapping("/{id}")
	public @ResponseBody JsonResponse updateGenre(@PathVariable int id, @RequestBody Genre g) {
//		u = genreRepository.save(u);
		return saveGenre(g);
//		return u;
	}

	private @ResponseBody JsonResponse saveGenre(Genre g) {
		JsonResponse jr = null;
		try {
			genreRepository.save(g);
			jr = JsonResponse.getInstance(g);
		} catch (DataIntegrityViolationException dive) {
			// TODO better way to handle exceptions
			jr = JsonResponse.getInstance(dive);
			jr.setErrors(dive.getMessage());
		}
		return jr;
	}

	// delete an genre
	@DeleteMapping("/{id}")
	public @ResponseBody JsonResponse removeUser(@PathVariable int id) { // remove the genre by id
		JsonResponse jr = null;
		Optional<Genre> a = genreRepository.findById(id);
		if (a.isPresent()) {
			genreRepository.deleteById(id);
			jr = JsonResponse.getInstance(a);
		} else {
			jr = JsonResponse.getInstance("User ID " + id + " was not successful deleted.");
		}
		return jr;
	}
//	// get genre by Gender
//	@GetMapping("/getByGender")
//	public @ResponseBody JsonResponse getgenreByGender(@RequestBody Genre genre) { // returns the user
//		return JsonResponse.getInstance(genreRepository.findByGender(genre.getGender()));
//	}
}
