package com.bmdb.web;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bmdb.business.Movie;
import com.bmdb.business.MovieRepository;
import com.bmdb.util.JsonResponse;

@Controller
@RequestMapping(path = "/movies")
public class MovieController {
	// This means to get the bean called movieRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired // like static method, no new() required, creating a bean (big POJO)
	private MovieRepository movieRepository;

	// get all movies
	@GetMapping("/")
	public @ResponseBody JsonResponse getAllMovies() {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(movieRepository.findAll()); // returns all instance of movie type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get movies - pagination version
	@GetMapping("")
	public @ResponseBody JsonResponse getMovies(@RequestParam int start, @RequestParam int limit) {
		JsonResponse jr = null; // instantiates JsonResponse object called "jr"
		try {
			jr = JsonResponse.getInstance(movieRepository.findAll(PageRequest.of(start, limit))); // returns all
																									// instance
																									// of movie type
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// get method using @RequestParam
//	@GetMapping("/get") // @RequestParam - have to add "?id=?"
//	public @ResponseBody Optional<Movie> getMovieById(@RequestParam int id) { // returns the Movie
////		Optional<Movie> u = MovieRepository.findById(id);
//		return getMovie(id); // calls path variable get method
//	}

	// get method using path variable
	@GetMapping("/{id}")
	public @ResponseBody JsonResponse getMovie(@PathVariable int id) { // returns the Movie
		JsonResponse jr = null; // instantiates JsonResponse as an object
		try {
			Optional<Movie> u = movieRepository.findById(id);
			if (u.isPresent()) {
				// good call to database - return a valid Movie
				jr = JsonResponse.getInstance(u); // return Movie object
			} else {
				jr = JsonResponse.getInstance(new Exception("No Movie Found for ID: " + id));
			}
		} catch (Exception ex) {
			jr = JsonResponse.getInstance(ex);
		}
		return jr;
	}

	// add an Movie
	@PostMapping(path = "/")
	public @ResponseBody JsonResponse addNewMovie(@RequestBody Movie a) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET (read) or @RequestBody
		// POST (update and delete)
		// request
//		return u;
//		JsonResponse jr = null;
//		jr = JsonResponse.getInstance(saveMovie(u));
		return saveMovie(a);
	}

	// update an Movie - changed from Post to PutMapping
	@PutMapping("/{id}")
	public @ResponseBody JsonResponse updateMovie(@PathVariable int id, @RequestBody Movie a) {
//		u = MovieRepository.save(u);
		return saveMovie(a);
//		return u;
	}

	private @ResponseBody JsonResponse saveMovie(Movie a) {
		JsonResponse jr = null;
		try {
			movieRepository.save(a);
			jr = JsonResponse.getInstance(a);
		} catch (DataIntegrityViolationException dive) {
			// TODO better way to handle exceptions
			jr = JsonResponse.getInstance(dive);
			jr.setErrors(dive.getMessage());
		}
		return jr;
	}

	// delete an Movie
	@DeleteMapping("/{id}")
	public @ResponseBody JsonResponse removeUser(@PathVariable int id) { // remove the Movie by id
		JsonResponse jr = null;
		Optional<Movie> a = movieRepository.findById(id);
		if (a.isPresent()) {
			movieRepository.deleteById(id);
			jr = JsonResponse.getInstance(a);
		} else {
			jr = JsonResponse.getInstance("User ID " + id + " was not successful deleted.");
		}
		return jr;
	}

	// get Movie by rating
	@GetMapping("/getByRating")
	public @ResponseBody JsonResponse getMovieByRating(@RequestBody Movie Movie) { // returns all movies by rating
		return JsonResponse.getInstance(movieRepository.findByRating(Movie.getRating()));
	}
}
